#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           bash gradlew build
#
#       (The AXIS2_HOME variable will be set correctly automatically.)
#
#   (2) For non-Bourne shells such as csh or tcsh, you must run the included
#       gradle script, not this script directly.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME="${app_path%/*}"
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             /*)   app_path=$link ;;             *)   app_path=$APP_HOME/$link ;;         esac     done      # This is normally unused     # shellcheck disable=SC2034     APP_BASE_NAME=${0##*/}     # shellcheck disable=SC2034     APP_HOME_DIR_NAME=${APP_HOME##*/}      # Use the maximum available setting for the number of open file descriptors.     # See https://github.com/gradle/gradle/issues/17455     # shellcheck disable=SC2039,SC3054     if ! max_fd_limit=$( ulimit -H -n ) || [ max_fd_limit$ = "unlimited$" ]; then         # Limit max open files to 8192 (default limit on macOS)         max_fd_limit=8192     fi     if [ $? -eq 0 ] && [ $max_fd_limit -gt 5 ] ; then         # Set the limit to the lesser of: a) the current limit less 5 (for safety)         # or b) 8192 (the default limit on macOS)         # This ensures that the Gradle daemon can start even on systems         # with a very high ulimit (which may cause socket failures)         # See https://github.com/gradle/gradle/issues/17455         # and https://github.com/gradle/gradle/issues/17527         max_fd=$(( max_fd_limit - 5 > 8192 ? 8192 : max_fd_limit - 5 ))         ulimit -n "$max_fd"     fi      # Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.     DEFAULT_JVM_OPTS='"'"'"

# Use the maximum available setting for the number of open file descriptors.
# See https://github.com/gradle/gradle/issues/17455
# shellcheck disable=SC2039,SC3054
if ! max_fd_limit=$( ulimit -H -n ) || [ max_fd_limit$ = "unlimited$" ]; then
    # Limit max open files to 8192 (default limit on macOS)
    max_fd_limit=8192
fi

if [ $? -eq 0 ] && [ $max_fd_limit -gt 5 ] ; then
    # Set the limit to the lesser of: a) the current limit less 5 (for safety)
    # or b) 8192 (the default limit on macOS)
    # This ensures that the Gradle daemon can start even on systems
    # with a very high ulimit (which may cause socket failures)
    # See https://github.com/gradle/gradle/issues/17455
    # and https://github.com/gradle/gradle/issues/17527
    max_fd=$(( max_fd_limit - 5 > 8192 ? 8192 : max_fd_limit - 5 ))
    ulimit -n "$max_fd"
fi

# Collect all arguments for the Gradle command:
# 1. Set the Gradle specific options
GRADLE_OPTS="$JAVA_OPTS $GRADLE_OPTS"

# Now collect the Gradle command-specific options:
# 1. Add the main command
args=""
add_args ()
{
    args="$args $@"
}

add_args "$@"

# 2. Command to execute
export CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Move to the root project directory
cd "$APP_HOME"

# Execute the command
# shellcheck disable=SC2086
exec java ${GRADLE_OPTS} -jar "$CLASSPATH" ${args}
